services:

  {{ env_name }}-{{ project_name }}:
    image: {{ image_name }}
    container_name: {{ env_name }}-{{ project_name }}
    restart: 'no'
    ports:
      - {{ external_port }}:80
    volumes:
      - /Repos/Static-Websites/{{ relative_project_root }}:/var/www/html
      - type: bind
        source: {{ deploy_directory }}/nginx.{{ env_name }}.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - web-static-network

networks:
  web-static-network:
    name: web-static-network
    external: true