services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443
      - 8000:8000
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
volumes:
  data: