---
api_host: "proxbox"
node: "proxbox"

# Set the name of your local storage inside Proxbox.
# Remember, this is for the Proxbox VM inside your homelab Proxmox instance
# So it is most likely `local-lvm` rather than `local-zfs`, as you will not need dual boot drives for Proxbox which is just used for development
local_storage_name: "local-lvm"

modules:
  truenas_scale:
    # Change this to false if you do not want a TrueNAS Scale VM
    enabled: true
    name: truenas-scale
    memory: 8196
    cores: 4
    disk_size: 12
    cpu_type: host
    bios: SeaBIOS
    machine_type: q35
    # Default to use a network bridge called `vmbr10`, which you will have created if you followed the instructions for setting up a separate NIC
    network_bridge: vmbr10
    scsi_controller: virtio-scsi-single
    iso_file_name: "TrueNAS-SCALE-22.12.3.3.iso"
    hba_resource_mapping_name: "HBA"
    boot_order: 
      - "scsi0"
      - "ide2"

  docker:
    # Change this to false if you do not want a docker VM
    enabled: true
    name: docker
    memory: 8196
    cores: 4
    disk_size: 30
    cpu_type: x86-64-v2-AES
    bios: ovmf
    machine_type: q35
    network_bridge: vmbr0
    scsi_controller: virtio-scsi-single
    iso_file_name: "debian-12.1.0-amd64-netinst.iso"
    boot_order: 
      - "scsi0"
      - "ide2"