version: '3'
services:

  prod-passwordpusher:
    container_name: prod-passwordpusher
    image: docker.io/pglombardo/pwpush:release
    environment:
      DATABASE_URL: "sqlite3:db/db.sqlite3"
      PWP__PW__EXPIRE_AFTER_VIEWS_DEFAULT: 3
      PWP__PW__EXPIRE_AFTER_VIEWS_MAX: 10
      PWP__PW__EXPIRE_AFTER_DAYS_DEFAULT: 2
      PWP__PW__EXPIRE_AFTER_DAYS_MAX: 10
      PWP__OVERRIDE_BASE_URL: "https://your.domain.com"
      PWP__TIMEZONE: "Europe/Stockholm"
      PWP__DEFAULT_LOCALE: "sv"
      PWP__THEME: 'darkly'

      PWP__GEN__MIN_SYLLABLE_LENGTH: 5
      PWP__GEN__MAX_SYLLABLE_LENGTH: 8
      PWP__GEN__SEPARATORS: "-_=%#"

      PWP__BRAND__TITLE: "Your Password Pusher Title"
      PWP__BRAND__TAGLINE: "Your Password Pusher Tagline"
    ports:
      - "{{ PORTS.PasswordPusher }}:5100"