---
- name: Enable root SSH login
  become: true
  become_method: su
  become_user: root
  
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin yes"
    backup: true
    state: present
  notify:
    - restart ssh