---
- name: Setup controller
  become: true
  hosts: controller
  tasks:
    - name: Install NFS kernel server to access NFS shares
      ansible.builtin.apt:
        name: nfs-kernel-server
        state: present
    
    - name: Set up the mounts
      ansible.posix.mount:
        src: "{{ item.src }}"
        path: "{{ item.path }}"
        opts: "{{ item.opts }}"
        boot: true
        state: mounted
        fstype: cifs
      with_items: "{{ controller_smb_mounts }}"