---
- name: Pre-setup of Proxmox VE
  become: true
  become_user: root
  hosts: homelab_proxmox
  tasks:
    # References:
    # https://pve.proxmox.com/wiki/Package_Repositories#sysadmin_no_subscription_repo
    # https://pve.proxmox.com/wiki/Package_Repositories#sysadmin_enterprise_repo
    - name: Disable Enterprise repositories
      block:
        - name: Add no-subscription repo source
          ansible.builtin.blockinfile:
            path: /etc/apt/sources.list
            block: |
              # Proxmox VE pve-no-subscription repository provided by proxmox.com,
              # NOT recommended for production use
              deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
            state: present

        - name: Disable Enterprise repository
          ansible.builtin.replace:
            path: /etc/apt/sources.list.d/pve-enterprise.list
            regexp: '^deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
            replace: '# deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'

        - name: Replace ceph repository
          ansible.builtin.replace:
            path: /etc/apt/sources.list.d/ceph.list
            regexp: '^deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise'
            replace: |-
              # deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise
              
              # No-Subscription repository
              deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription

        - name: Validate that it worked by updating the packages
          ansible.builtin.apt:
            force_apt_get: true
            update_cache: true