---
# The server itself, running Proxmox
homelab_proxmox:
  hosts:
    YOUR_HOMELAB_PROXMOX_IP_HERE:
      ansible_user: "{{ vault_proxmox_ssh_username }}"
      ansible_password: "{{ vault_proxmox_ssh_password }}"

# The TrueNAS Scale VM inside Proxmox
homelab_truenas:
  hosts:
    YOUR_HOMELAB_TRUENAS_SCALE_VM_IP_HERE

# The Docker VM inside Proxmox
homelab_docker:
  hosts:
    YOUR_HOMELAB_DOCKER_VM_IP_HERE:
      ansible_user: "{{ vault_docker_ssh_username }}"
      ansible_password: "{{ vault_docker_ssh_password }}"
      ansible_become_pass: "{{ vault_docker_ssh_password }}"

# The Home Assistant VM inside Proxmox
homelab_home_assistant:
  hosts:
    YOUR_HOMELAB_HOME_ASSISTANT_VM_IP_HERE

# The Ansible Controller, i.e. WSL if you are using it
# Otherwise the Linux controller from which you execute the ansible scripts
controller:
  hosts:
    controller_host:
      ansible_connection: local
      ansible_become_pass: "{{ control_node_root_password }}"